languange: java
sudo: false

jdk:
  - oraclejdk8

before_install:
  - cp .travis/maven-settings.xml ~/.m2/settings.xml

install: true

script:
  - ./mvnw -f releng/aggregator/pom.xml verify

after_failure:
  - find . -type f -name "*.log" -exec .travis/dump-log.sh {} \;